export default function Footer() {
  return (
    <footer className="border-t border-rink-border py-8 text-sm text-slate-500">
      <div className="mx-auto max-w-7xl px-4">
        <p>
          DraftCrease is an independent fantasy hockey tool and is not affiliated with the NHL or
          any of its member clubs. Stats sourced from the NHL's public API; recommendations are
          generated by our own scoring model, not official projections.
        </p>
        <p className="mt-2 text-slate-600">© {new Date().getFullYear()} DraftCrease</p>
      </div>
    </footer>
  );
}
