import { Link } from 'react-router-dom';

export default function Footer() {
  return (
    <footer className="border-t border-rink-border py-8 text-sm text-slate-500 print:hidden">
      <div className="mx-auto max-w-7xl px-4">
        <p>
          DraftCrease is an independent fantasy hockey tool and is not affiliated with the NHL or
          any of its member clubs. Stats sourced from the NHL's public API; recommendations are
          generated by our own scoring model, not official projections.
        </p>
        <div className="mt-2 flex items-center gap-3 text-slate-600">
          <span>© {new Date().getFullYear()} DraftCrease</span>
          <span aria-hidden="true">·</span>
          <Link to="/privacy" className="hover:text-slate-400 hover:underline">
            Privacy Policy
          </Link>
        </div>
      </div>
    </footer>
  );
}
